### ISSUE TITLE
Styling Inconsistencies

### ISSUE THREAD

**Issue by ethangambles** [ainc/ainc-gatsby-sanity#198]
Sometimes when we push new code, it affects styling for some pages (buttons, images, etc) even if those pages are not changed. Need to figure out why that is.
@raney24

**Comment by ethangambles** [comment]
Most common examples: /learn/, /internships/

**Comment by ethangambles** [comment]
A common theme that I see is that the issues are components (<BrandButton>, <Diagonal>, etc). Could that have an effect on how their styling is applied, maybe at build?

**Comment by raney24** [comment]
@ethangambles So, I think it is definitely something to do with the `styled-components`, but we actually need to use this because of the way that we make that component. It has to use a background-image that is passed in as a prop, and I'm not sure there's a way to pass anything to a `.scss` file. 

I think I fixed it by adding the `space-escaped` character code for "space" to force the `content:` property since that was not rendering at all. 

It's working here: https://198-styling-inconsistencies--ainc-gatsby-sanity.netlify.app/internships/
but not here: https://198-styling-inconsistencies--ainc-gatsby-sanity.netlify.app/learn/

I haven't changed the learn page, could you fix that one and let me know if it's working for you?

**Comment by ethangambles** [comment]
@raney24 That worked for me on the internships page, but I couldn't get it to work for the learn page. That solution also doesn't explain why BrandButton doesn't work sometimes, which does not use a `:before` from what I can tell. 

I do think it's because of the styled components and I will keep looking

**Comment by raney24** [comment]
@ethangambles Can you double check it's working on your end? I recently made a push - frustratingly, the fix was to add a colon...
This does not work:
`&:before`
This does work:
`&::before`

This worked for me, let's wait to see if the next couple of builds holds true.
