### ISSUE TITLE
Netlify site not deploying new commits

### ISSUE THREAD

**Issue by WillGarman** [ainc/ainc-gatsby-sanity#23]
Seems like Netlify is getting caught up on the GraphQL when trying to deploy new commits 

![image](https://user-images.githubusercontent.com/73144742/200894850-5d7ad7c8-f281-4dd1-b57c-a4274ee69096.png)

It is the same error on all of these commits
![image](https://user-images.githubusercontent.com/73144742/200894665-53d25557-02e5-42ab-96ad-7b75af269d45.png)

**Comment by raney24** [comment]
@WillGarman have you tried clearing the cache and building from Netlify? 
<img width="702" alt="Screen Shot 2022-11-10 at 1 31 53 PM" src="https://user-images.githubusercontent.com/4423998/201177833-5bba6e36-6fe6-489c-b9d5-c16c6720b0c6.png">

I'm going to let you try since I'm kind of on and offline for a bit. 

cc @colinsmith3 if you want to try this as well

**Comment by WillGarman** [comment]
I can try here in a little while, I was just nervous to touch any of the Netlify stuff 😅

**Comment by WillGarman** [comment]
Ended up just needing to run `sanity graphql deploy` on a local bootup to get the current graphql deployed, I guess that command just hadn't been ran by anybody in the past couple of commits
![image](https://user-images.githubusercontent.com/73144742/201277025-1e1a585e-6d54-4ded-a297-b370dfd00eca.png)
